[extend]
useDefault = true

[allowlist]
description = "Ignore local dev configs, test fixtures, and mock files"
paths = [
    '''infrastructure/local/dex-config\.yaml''',
    '''tests/unit/fleet/test_expansion_loop\.py''',
    '''bandit-tests\.json''',
    '''src/coreason_ecosystem/auth/distr_provisioning\.py''',
    '''infrastructure/local/compose\.yaml'''
]
commits = [
    "476ed49564507d2766fedb1416441922bbb5d378",
    "50ab55e698e8d8c05a5f28fc708dbbfdaccf2c05",
    "2ec4d03f3a31fb93c7bd88ec69763e404de16cb5",
    "e6d9421a63179844185a28b4146b444dbf5e30ab",
    "cff5e0479384d70a3a7076abbc8807c000f77708",
    "8f088b02df911254f643380531a6bc7d6a8ce709"
]
