site_name: CoReason Ecosystem

theme:
  name: material
  palette:
    primary: black
    accent: deep purple

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
