{{- if and (eq .Values.global.environment "production") .Values.runtime.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-runtime-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-runtime
  minReplicas: {{ .Values.runtime.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.runtime.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.runtime.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
